package models

import "time"

// EventType categorizes network occurrences
type EventType string

const (
	EventDNS      EventType = "DNS"
	EventPortScan EventType = "PORT_SCAN"
	EventARP      EventType = "ARP"
	EventPhysical EventType = "PHYSICAL"
	EventAlert    EventType = "THREAT_ALERT"
	EventProxy    EventType = "PROXY"
	EventVM       EventType = "VM"
)

// NetworkEvent represents an observation generated by an intelligence module
type NetworkEvent struct {
	ID          string         `json:"id"`
	Type        EventType      `json:"type"`
	Source      string         `json:"source"`
	Destination string         `json:"destination"`
	Metadata    map[string]any `json:"metadata"`
	Timestamp   time.Time      `json:"timestamp"`
}
